# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.network "private_network", ip: "10.0.0.13"
  config.vm.hostname = "worker-node03"
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
     vb.cpu = "2"
  end
end
